### ISSUE TITLE
Atom v1.13.0: deprecation notice: atom-text-editor elements no longer encapsulated within shadow DOM boundary

### ISSUE THREAD

**Issue by gamecubate** [mikol/filter-syntax#2]
I've been using this (great) theme for months now. All seemed well until this morning when Atom (1.13.0) issued the following deprecation notice:

```Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--.```

Possibly as part of the same issue -- although not 100% sure -- the caret is no longer visible on alerts such as those shown for new file creation, file renaming, folder creation, etc.

**Comment by mikol** [comment]
Thanks for the report, @gamecubate. I’m happy to hear that you like the theme. I have some local changes that partially address the deprecation warning you are seeing. And I am going to address the remaining issues ASAP. Look for an updated version in a week or so. I apologize for my tardy reply.

**Comment by gamecubate** [comment]
No problem. Looking forward to the update. Will post if issue (partially or not) persists.

**Comment by mikol** [comment]
@gamecubate 

I renamed the deprecated CSS selectors.

I can’t reproduce the caret issue you mention. I also haven’t seen it before myself. What Atom version are you on now? Which platform (Linux, OS X, Windows, …)?

**Comment by gamecubate** [comment]
Atom 1.15.0, OSX 10.11.5. filter-syntax 0.2.4. Caret still not visible. Will survive. :)
